{
    'name': 'CEDL E-Learning',
    'version': '19.0.3.0.0',
    'summary': 'Boletim por matéria: 4 bimestres, média e aprovação configuráveis',
    'category': 'eLearning',
    'author': 'CE Dias Lima',
    'website': 'https://c-edl.com',
    'license': 'LGPL-3',
    'depends': ['website_slides', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/cedl_turma_views.xml',
        'views/cedl_materia_views.xml',
        'views/slide_channel_views.xml',
        'views/slide_slide_views.xml',
        'views/cedl_nota_views.xml',
        'views/menus.xml',
    ],
    'post_init_hook': 'post_init_sync_professors',
    'application': True,
    'installable': True,
}
